apiVersion: v2
name: greeting
description: A simple greeting plugin for Rancher Dashboard
version: 0.1.0
type: application
annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/namespace: cattle-ui-plugin-system
  catalog.cattle.io/release-name: greeting
  catalog.cattle.io/ui-component: plugin
  catalog.cattle.io/display-name: "Greeting Plugin"
  catalog.cattle.io/kube-version: ">= 1.16.0-0"
  catalog.cattle.io/rancher-version: ">= 2.10.0-0"
  catalog.cattle.io/os: linux 