annotations:
  catalog.cattle.io/namespace: cattle-ui-plugin-system
  catalog.cattle.io/os: linux
  catalog.cattle.io/scope: management
  catalog.cattle.io/ui-component: plugins
  catalog.cattle.io/kube-version: ">= 1.16.0-0"
  catalog.cattle.io/rancher-version: ">= 2.10.0-0"
  catalog.cattle.io/ui-extensions-version: ">= 3.0.0 < 4.0.0"
apiVersion: v2
name: krew-workstation
description: Krew Workstation - kubectl plugin manager for Rancher Dashboard
type: application
version: 0.1.0
appVersion: "1.0"
keywords:
  - krew
  - kubectl
  - rancher
  - plugins
home: https://github.com/aeltai/krew-workstation
sources:
  - https://github.com/aeltai/krew-workstation
maintainers:
  - name: aeltai
